import Head from 'next/head';
import Navbar from '../components/Navbar';
import TodoForm from '../components/TodoForm';
import TodoList from '../components/TodoList';
import { getTodos } from "../lib/db";

export default async function Home(){

  const todo = await getTodos();
  const parsedTodos = todo ? todo : null;
  return (
    <div className='max-w-[1000px] m-auto bg-gray-50'>
      <Head>
        <title>Todo App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navbar />
      <main className='border-b'>
        <TodoForm />
        <TodoList data={parsedTodos}/>
      </main>
    </div>
  );
};
