import Head from 'next/head';
import Navbar from '../components/Navbar';
import TodoForm from '../components/TodoForm';
import TodoList from '../components/TodoList';
import { getTodos } from "../lib/db";

export default async function Home() {
  const todos = await getTodos();
  const parsedTodos = todos ? todos : null;

  return (
    <div className="container max-w-4xl mx-auto bg-gray-50 mr-40 ml-40">
      <main className="main border-b p-4 mx-auto max-w-md">
        <Head>
          <title>Todo App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Navbar />

        <section className="todo-section flex flex-col gap-4 items-center">
          <TodoForm />
          <TodoList data={parsedTodos} />
        </section>
      </main>
    </div>
  );
}
