import type { NextPage, GetServerSideProps } from 'next';
import Head from 'next/head';
import Navbar from '../components/Navbar';
import TodoForm from '../components/TodoForm';
import TodoList from '../components/TodoList';
import { PrismaClient } from '@prisma/client';

const Home = ({ todos }: any) => {
  const parsedTodos = JSON.parse(todos);
  return (
    <div className='max-w-[1000px] m-auto bg-gray-50'>
      <Head>
        <title>Todo App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navbar />
      <main className='border-b'>
        <TodoForm />
        <TodoList todos={parsedTodos} />
      </main>
    </div>
  );
};

export const getServerSideProps: GetServerSideProps = async () => {
  const prisma = new PrismaClient();

  const data = await prisma.todo.findMany();

  if (!data) {
    return { props: { message: 'Nothing to show' } };
  }
  return { props: { todos: JSON.stringify(data) } };
};

export default Home;
